In [8]:
from pandas import read_csv
from sklearn.linear_model import LinearRegression
import numpy as np

In [9]:
data = np.array([
    [2.0, 3.5, 10.2],
    [1.5, 2.8, 8.5],
    [3.2, 4.1, 12.0],
    [4.0, 5.0, 15.3],
    [2.8, 3.7, 11.0],
    [3.5, 4.5, 13.2],
    [1.8, 2.9, 9.0],
    [2.5, 3.6, 10.8],
])


In [10]:
X = data[:, :-1]
y = data[:, -1]
X

array([[2. , 3.5],
       [1.5, 2.8],
       [3.2, 4.1],
       [4. , 5. ],
       [2.8, 3.7],
       [3.5, 4.5],
       [1.8, 2.9],
       [2.5, 3.6]])

In [11]:
X_new = np.column_stack((np.ones(X.shape[0]), X))
X_new.shape


(8, 3)

$$X^T * y * (X^T * X)^{-1}$$

In [12]:
w = X_new.T @ y @ np.linalg.inv(X_new.T @ X_new)
w

array([0.54103093, 0.22693122, 2.68565174])

In [18]:
x = [1, 2.6, 6]
w @ x

np.float64(17.244962575908083)

In [15]:
lg = LinearRegression()
lg.fit(X, y)
lg.intercept_, lg.coef_,

(np.float64(0.5410309278350578), array([0.22693122, 2.68565174]))

In [19]:
lg.predict([[2.6, 6]])

array([17.24496258])