In [97]:
from pandas import read_csv, DataFrame
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import numpy as np

In [122]:
m = np.array([
    [3, 7, 150],
    [6, 19, 250],
    [1, 4, 100],
    [2, 3, 147],
    [8, 4, 168]
])
x = m - m.mean(axis=0)
y = (x.T @ x) / 4
print(y)
np.linalg.eig(y)
#print()
#print(m.mean(axis=0))



[[   8.5     7.25  107.  ]
 [   7.25   44.3   320.5 ]
 [ 107.    320.5  2997.  ]]


EigResult(eigenvalues=array([3.03518231e+03, 2.36437024e+00, 1.22533237e+01]), eigenvectors=array([[-0.03538393, -0.87308343,  0.48628522],
       [-0.10656708, -0.48051924, -0.87048533],
       [-0.99367572,  0.08262319,  0.07603929]]))

In [118]:
pca = PCA(n_components=3)
pca.fit(m)
pca.explained_variance_

array([3.03518231e+03, 1.22533237e+01, 2.36437024e+00])

In [121]:
pca.components_

array([[ 0.03538393,  0.10656708,  0.99367572],
       [-0.48628522,  0.87048533, -0.07603929],
       [ 0.87308343,  0.48051924, -0.08262319]])

In [72]:
df = read_csv("housing_data_na.csv")
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [124]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [123]:
from sklearn.preprocessing import StandardScaler

In [126]:
scaler = StandardScaler()
cols = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']
df[cols] = scaler.fit_transform(df[cols])

In [127]:
df.head()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.400818  0.273342 -1.259620 -0.271237 -0.134687  0.423161 -0.134014   
1 -0.398535 -0.479051 -0.569724 -0.271237 -0.745475  0.202245  0.357849   
2 -0.398537 -0.479051 -0.569724 -0.271237 -0.745475  1.298216 -0.281214   
3 -0.397984 -0.479051 -1.278462 -0.271237 -0.842847  1.029962 -0.830521   
5 -0.398258 -0.479051 -1.278462 -0.271237 -0.842847  0.215156 -0.367380   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  MEDV  
0  0.135851 -0.974609 -0.656944 -1.496303  0.430740 -1.067126  24.0  
1  0.554334 -0.858633 -0.978184 -0.340879  0.430740 -0.497196  21.6  
2  0.554334 -0.858633 -0.978184 -0.340879  0.385097 -1.197278  34.7  
3  1.076829 -0.742657 -1.097162  0.075073  0.405283 -1.346610  33.4  
5  1.076829 -0.742657 -1.097162  0.075073  0.399564 -1.035615  28.7

In [128]:
df[cols].describe()

CRIM            ZN         INDUS          CHAS           NOX  \
count  3.940000e+02  3.940000e+02  3.940000e+02  3.940000e+02  3.940000e+02   
mean  -1.803408e-16  2.930538e-17 -5.410224e-17 -6.311928e-17  5.410224e-16   
std    1.001271e+00  1.001271e+00  1.001271e+00  1.001271e+00  1.001271e+00   
min   -4.008184e-01 -4.790512e-01 -1.527752e+00 -2.712369e-01 -1.453635e+00   
25%   -3.925889e-01 -4.790512e-01 -8.509001e-01 -2.712369e-01 -8.871071e-01   
50%   -3.722505e-01 -4.790512e-01 -3.537692e-01 -2.712369e-01 -1.346874e-01   
75%   -2.765433e-02  4.344402e-02  1.028921e+00 -2.712369e-01  6.265843e-01   
max    9.279567e+00  3.700910e+00  2.426106e+00  3.686813e+00  2.813028e+00   

                 RM           AGE           DIS           RAD           TAX  \
count  3.940000e+02  3.940000e+02  3.940000e+02  3.940000e+02  3.940000e+02   
mean   3.020708e-16 -1.442726e-16  9.017040e-18  7.213632e-17  3.606816e-17   
std    1.001271e+00  1.001271e+00  1.001271e+00  1.001271e+00  1.001271e+00   
min   -3.900475e+00 -2.370734e+00 -1.276616e+00 -9.746089e-01 -1.305373e+00   
25%   -5.749047e-01 -8.421892e-01 -8.087995e-01 -6.266815e-01 -7.506392e-01   
50%   -1.126315e-01  3.147656e-01 -2.891675e-01 -5.107057e-01 -4.546821e-01   
75%    4.669136e-01  9.089504e-01  6.257112e-01  1.692835e+00  1.544144e+00   
max    3.586272e+00  1.115389e+00  3.970231e+00  1.692835e+00  1.811844e+00   

            PTRATIO             B         LSTAT  
count  3.940000e+02  3.940000e+02  3.940000e+02  
mean   3.967498e-16 -9.017040e-17 -3.967498e-16  
std    1.001271e+00  1.001271e+00  1.001271e+00  
min   -2.744160e+00 -3.991155e+00 -1.512383e+00  
25%   -5.257471e-01  2.042904e-01 -7.732560e-01  
50%    2.599410e-01  3.779196e-01 -2.012716e-01  
75%    7.683274e-01  4.307401e-01  5.957390e-01  
max    1.600232e+00  4.307401e-01  3.452579e+00

In [75]:
df.dropna(inplace=True)

In [129]:
X = df.drop(columns=['MEDV']).values
X.shape

(394, 13)

In [133]:
pca = PCA(n_components=9)
pca.fit(X)
sum(pca.explained_variance_ratio_)

np.float64(0.9517502132768069)

In [136]:
X_t = pca.transform(X)

In [135]:
pca.explained_variance_ratio_ 

array([0.47208858, 0.10796894, 0.09726819, 0.06846472, 0.06078869,
       0.05090028, 0.04280203, 0.02948851, 0.02198028])

In [93]:
pca.explained_variance_ / sum(pca.explained_variance_)

array([0.80949199, 0.1598107 , 0.02195717, 0.00719827, 0.00154186])

In [89]:
pca.components_

array([[ 3.04131711e-02, -4.37853121e-02,  2.90970651e-02,
        -4.76893283e-05,  4.48504548e-04, -1.27074534e-03,
         8.31718185e-02, -6.50746554e-03,  4.43912657e-02,
         9.53079807e-01,  5.48944711e-03, -2.79954366e-01,
         2.47637982e-02],
       [-9.95894976e-03,  2.64062522e-04,  6.04030523e-03,
         1.94444999e-04, -1.27830997e-05, -5.32442228e-04,
        -1.21063793e-03, -2.33102902e-04,  6.63023413e-03,
         2.81897551e-01,  2.07515245e-03,  9.59322242e-01,
        -6.98303758e-03],
       [ 1.10252384e-02, -6.61974984e-01,  8.54219547e-02,
         7.90292188e-04,  1.71794828e-03, -5.01613850e-03,
         7.31446553e-01, -4.44227328e-02, -4.31710647e-03,
        -9.14345566e-02,  1.38713998e-02,  2.81867142e-02,
         8.93792777e-02],
       [ 2.96294898e-02,  7.43399003e-01, -6.16457859e-03,
         8.17002551e-04,  7.16588517e-04,  6.69650325e-03,
         6.64983328e-01, -3.30283512e-03, -2.19278466e-02,
        -2.22034156e-02, -3.48188234e

In [96]:
X_t

array([[-117.55042751,    5.69846131,    2.61866804,    5.04056622,
          -1.50136799],
       [-166.79441782,   -9.53415539,   30.26321147,    2.00977914,
           0.54185014],
       [-167.26297638,  -13.38177083,   16.66818223,  -10.07915337,
           0.2110937 ],
       ...,
       [-137.30040817,   -0.76227809,   26.39897302,   -0.25613773,
          -0.77690593],
       [-136.19607439,   -0.75615063,   36.5524017 ,    9.10853912,
          -2.05093335],
       [-135.35054673,   -4.07006103,   35.2783931 ,    7.98668876,
          -1.83636067]])

In [137]:
df_pca = DataFrame(data = X_t, columns=[f'C{i+1}' for i in range(9)])
df_pca.head()

C1        C2        C3        C4        C5        C6        C7  \
0 -2.085595  0.741513  0.433169 -0.906496 -0.443648  0.303519  0.317839   
1 -1.453701  0.622528 -0.661109 -0.512670  0.094390 -0.269910  0.518363   
2 -2.084315  0.629364  0.128927 -0.687370  0.932393 -0.408566  0.482818   
3 -2.614464  0.033503 -0.205639 -0.288031  1.085508 -0.637605  0.612359   
4 -2.207503  0.032624 -0.734708 -0.177539  0.544420 -0.566460  0.619849   

         C8        C9  
0 -0.320345 -0.440253  
1  0.185702 -0.147165  
2 -0.149642  0.064080  
3 -0.314256 -0.352925  
4 -0.158510 -0.464790

In [138]:
df_pca['MEDV'] = df['MEDV']

In [140]:
df_pca.corr()

C1            C2            C3            C4            C5  \
C1    1.000000e+00  8.616759e-17  4.716201e-17  2.488185e-16 -1.247533e-16   
C2    8.616759e-17  1.000000e+00 -3.350356e-16 -3.317750e-16  3.355115e-16   
C3    4.716201e-17 -3.350356e-16  1.000000e+00  2.152806e-16  2.367844e-16   
C4    2.488185e-16 -3.317750e-16  2.152806e-16  1.000000e+00 -5.819340e-16   
C5   -1.247533e-16  3.355115e-16  2.367844e-16 -5.819340e-16  1.000000e+00   
C6    2.173300e-16 -7.641588e-16  7.485683e-16  8.500180e-16 -2.599112e-16   
C7    1.124385e-16  8.396966e-16 -1.157206e-15 -4.694809e-16  6.480327e-16   
C8   -2.390525e-16 -1.258074e-15  1.121288e-15  2.879952e-16 -5.918215e-16   
C9   -4.839278e-16 -2.227831e-15  2.560943e-15  1.125331e-15 -2.162018e-15   
MEDV -2.033149e-01 -8.015471e-02  1.892688e-01  1.029748e-01  8.551955e-03   

                C6            C7            C8            C9      MEDV  
C1    2.173300e-16  1.124385e-16 -2.390525e-16 -4.839278e-16 -0.203315  
C2   -7.641588e-16  8.396966e-16 -1.258074e-15 -2.227831e-15 -0.080155  
C3    7.485683e-16 -1.157206e-15  1.121288e-15  2.560943e-15  0.189269  
C4    8.500180e-16 -4.694809e-16  2.879952e-16  1.125331e-15  0.102975  
C5   -2.599112e-16  6.480327e-16 -5.918215e-16 -2.162018e-15  0.008552  
C6    1.000000e+00 -1.609559e-15  1.008322e-15  3.789670e-15  0.136420  
C7   -1.609559e-15  1.000000e+00 -1.884952e-15 -3.358490e-15  0.003097  
C8    1.008322e-15 -1.884952e-15  1.000000e+00  3.758880e-15 -0.044814  
C9    3.789670e-15 -3.358490e-15  3.758880e-15  1.000000e+00 -0.228252  
MEDV  1.364203e-01  3.096804e-03 -4.481415e-02 -2.282517e-01  1.000000

In [141]:
X = df_pca.drop(columns=['MEDV']).values
y = df['MEDV'].values

In [142]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
knn.fit(X, y)
knn.score(X, y)

0.836638929447183

In [139]:
model = ols('MEDV ~ C1 + C2 + C3 + C4 + C5 + C6 + C7 + C8 + C9', data= df_pca).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.166
Model:                            OLS   Adj. R-squared:                  0.141
Method:                 Least Squares   F-statistic:                     6.585
Date:                Sun, 02 Mar 2025   Prob (F-statistic):           1.41e-08
Time:                        17:02:04   Log-Likelihood:                -1080.2
No. Observations:                 307   AIC:                             2180.
Df Residuals:                     297   BIC:                             2218.
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     24.5804      0.475     51.735      0.000      23.645      25.515
C1            -0.7024      0.193     -3.646      0.000      -1.081      -0.323
C2            -0.6443      0.399     -1.616      0.107      -1.429       0.140
C3             1.5332      0.411      3.727      0.000       0.724       2.343
C4             0.9149      0.508      1.800      0.073      -0.086       1.915
C5             0.1409      0.554      0.254      0.799      -0.950       1.232
C6             1.5295      0.595      2.571      0.011       0.359       2.700
C7             0.0591      0.631      0.094      0.925      -1.182       1.300
C8            -0.4227      0.791     -0.535      0.593      -1.979       1.133
C9            -3.7908      0.873     -4.345      0.000      -5.508      -2.074
==============================================================================
Omnibus:                       36.620   Durbin-Watson:                   0.876
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.439
Skew:                           0.846   Prob(JB):                     5.00e-11
Kurtosis:                       3.918   Cond. No.                         4.56
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [80]:
X_t = pca.transform(X)
X_t.shape

(394, 5)

In [94]:
print(np.corrcoef(X_t.T))


[[ 1.00000000e+00  6.02590813e-16 -2.86077092e-16 -1.93489179e-15
   3.05789779e-16]
 [ 6.02590813e-16  1.00000000e+00  3.58426740e-15  7.36153025e-15
   3.73336610e-15]
 [-2.86077092e-16  3.58426740e-15  1.00000000e+00 -9.23728535e-17
  -1.33802987e-15]
 [-1.93489179e-15  7.36153025e-15 -9.23728535e-17  1.00000000e+00
   5.91319812e-15]
 [ 3.05789779e-16  3.73336610e-15 -1.33802987e-15  5.91319812e-15
   1.00000000e+00]]


In [95]:
y = df['MEDV'].values

X = df.dro

In [4]:
df.shape

(506, 14)

In [3]:
df.isna().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [73]:
df.dropna(inplace=True)

In [7]:
df.shape

(394, 14)

In [8]:
df.corr()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.188075  0.391552 -0.051970  0.416160 -0.227170  0.341311   
ZN      -0.188075  1.000000 -0.521256 -0.033357 -0.515660  0.343210 -0.568174   
INDUS    0.391552 -0.521256  1.000000  0.049820  0.762737 -0.403068  0.642387   
CHAS    -0.051970 -0.033357  0.049820  1.000000  0.076661  0.095308  0.072644   
NOX      0.416160 -0.515660  0.762737  0.076661  1.000000 -0.316563  0.732540   
RM      -0.227170  0.343210 -0.403068  0.095308 -0.316563  1.000000 -0.248670   
AGE      0.341311 -0.568174  0.642387  0.072644  0.732540 -0.248670  1.000000   
DIS     -0.365052  0.645359 -0.696569 -0.095037 -0.768137  0.218713 -0.753547   
RAD      0.608667 -0.298773  0.591944  0.014102  0.628170 -0.236057  0.443585   
TAX      0.560841 -0.305768  0.734204 -0.026513  0.679824 -0.320561  0.504472   
PTRATIO  0.265428 -0.422164  0.395691 -0.104995  0.210216 -0.390686  0.264968   
B       -0.386254  0.169894 -0.344788  0.068913 -0.384257  0.123320 -0.281990   
LSTAT    0.461906 -0.415041  0.598156 -0.037113  0.593655 -0.636226  0.601137   
MEDV    -0.397230  0.406822 -0.510829  0.173701 -0.459054  0.723951 -0.407470   

              DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  
CRIM    -0.365052  0.608667  0.560841  0.265428 -0.386254  0.461906 -0.397230  
ZN       0.645359 -0.298773 -0.305768 -0.422164  0.169894 -0.415041  0.406822  
INDUS   -0.696569  0.591944  0.734204  0.395691 -0.344788  0.598156 -0.510829  
CHAS    -0.095037  0.014102 -0.026513 -0.104995  0.068913 -0.037113  0.173701  
NOX     -0.768137  0.628170  0.679824  0.210216 -0.384257  0.593655 -0.459054  
RM       0.218713 -0.236057 -0.320561 -0.390686  0.123320 -0.636226  0.723951  
AGE     -0.753547  0.443585  0.504472  0.264968 -0.281990  0.601137 -0.407470  
DIS      1.000000 -0.477075 -0.529603 -0.228840  0.285168 -0.505036  0.279547  
RAD     -0.477075  1.000000  0.900000  0.441949 -0.444135  0.510868 -0.416638  
TAX     -0.529603  0.900000  1.000000  0.446961 -0.435457  0.572218 -0.508864  
PTRATIO -0.228840  0.441949  0.446961  1.000000 -0.179816  0.395006 -0.543809  
B        0.285168 -0.444135 -0.435457 -0.179816  1.000000 -0.383783  0.347256  
LSTAT   -0.505036  0.510868  0.572218  0.395006 -0.383783  1.000000 -0.743450  
MEDV     0.279547 -0.416638 -0.508864 -0.543809  0.347256 -0.743450  1.000000

In [ ]:
# PCA => giảm chiều
# Giá trị riêng, vector riêng

In [71]:
from sklearn.decomposition import PCA

In [ ]:
# vif he so phong dai


In [24]:
X.shape[1]

13

In [ ]:
Vif > 10 loai bien do

In [ ]:
[]

[('CRIM', 2.011941965712594),
 ('ZN', 2.852309927713017),
 ('INDUS', 14.263621604094793),
 ('CHAS', 1.147676919923875),
 ('NOX', 78.19587146837218),
 ('RM', 83.38739667510177),
 ('AGE', 22.40573051836839),
 ('DIS', 14.367438543452744),
 ('RAD', 13.986225022429808),
 ('TAX', 58.485821213801586),
 ('PTRATIO', 88.48314836650732),
 ('B', 21.04718393865385),
 ('LSTAT', 11.340925461230494)]

In [ ]:
# X Bien Doc lap
# y bien phu thuoc

In [10]:
X = df.drop(columns=['MEDV']).values
y = df['MEDV'].values
X.shape, y.shape

((394, 13), (394,))

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((295, 13), (99, 13), (295,), (99,))

In [44]:
lg = LinearRegression()
lg.fit(X_train, y_train)

LinearRegression()

In [45]:
lg.score(X_train, y_train), lg.score(X_test, y_test)

(0.8029402917859002, 0.6375912434392776)

In [46]:
lg.coef_, lg.intercept_

(array([-9.22842702e-02,  4.29959897e-02,  5.34671976e-02,  3.92603393e+00,
        -1.68602709e+01,  4.80137034e+00, -2.24883353e-02, -1.25023930e+00,
         2.72041247e-01, -1.36873774e-02, -8.79847205e-01,  7.95697615e-03,
        -4.01630394e-01]),
 np.float64(28.287022190177517))

In [17]:
from statsmodels.formula.api import ols

In [50]:
model = ols('MEDV ~ CRIM + ZN + INDUS + CHAS + NOX + RM + AGE + DIS + RAD + TAX + PTRATIO + B + LSTAT', data=df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.767
Model:                            OLS   Adj. R-squared:                  0.759
Method:                 Least Squares   F-statistic:                     96.29
Date:                Sun, 02 Mar 2025   Prob (F-statistic):          1.75e-111
Time:                        15:04:33   Log-Likelihood:                -1143.4
No. Observations:                 394   AIC:                             2315.
Df Residuals:                     380   BIC:                             2370.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     32.6801      5.681      5.752      0.000      21.509      43.851
CRIM          -0.0976      0.032     -3.007      0.003      -0.161      -0.034
ZN             0.0489      0.014      3.397      0.001       0.021       0.077
INDUS          0.0304      0.066      0.461      0.645      -0.099       0.160
CHAS           2.7694      0.925      2.993      0.003       0.950       4.588
NOX          -17.9690      4.243     -4.235      0.000     -26.311      -9.627
RM             4.2833      0.471      9.100      0.000       3.358       5.209
AGE           -0.0130      0.014     -0.898      0.370      -0.041       0.015
DIS           -1.4585      0.211     -6.912      0.000      -1.873      -1.044
RAD            0.2859      0.069      4.125      0.000       0.150       0.422
TAX           -0.0131      0.004     -3.324      0.001      -0.021      -0.005
PTRATIO       -0.9146      0.141     -6.506      0.000      -1.191      -0.638
B              0.0097      0.003      3.251      0.001       0.004       0.015
LSTAT         -0.4237      0.055     -7.700      0.000      -0.532      -0.315
==============================================================================
Omnibus:                      161.243   Durbin-Watson:                   1.247
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              904.814
Skew:                           1.657   Prob(JB):                    3.33e-197
Kurtosis:                       9.643   Cond. No.                     1.57e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.57e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Giả thiết
$$ H_0: X_i = 0$$
$$ H_1: X_i != 0$$
Biến INDUS và AGE có p-value > 0.05 Không thể bác bỏ giả thiết H0 -> tức 2 biến IDUX và AGE ko có ý nghĩa trong mô hình

# Chay mo hinh hoi qui loai bo bien TAX

In [40]:
df.drop(columns=['TAX'], inplace=True)

In [38]:
model = ols('MEDV ~ CRIM + ZN + INDUS + CHAS + NOX + RM + AGE + DIS + RAD + PTRATIO + B + LSTAT', data=df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.760
Model:                            OLS   Adj. R-squared:                  0.753
Method:                 Least Squares   F-statistic:                     100.7
Date:                Sun, 02 Mar 2025   Prob (F-statistic):          3.75e-110
Time:                        14:36:54   Log-Likelihood:                -1149.1
No. Observations:                 394   AIC:                             2324.
Df Residuals:                     381   BIC:                             2376.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     30.5693      5.720      5.345      0.000      19.323      41.815
CRIM          -0.0948      0.033     -2.884      0.004      -0.159      -0.030
ZN             0.0374      0.014      2.642      0.009       0.010       0.065
INDUS         -0.0740      0.059     -1.260      0.208      -0.189       0.041
CHAS           3.1650      0.929      3.405      0.001       1.337       4.993
NOX          -18.3680      4.297     -4.275      0.000     -26.816      -9.920
RM             4.3752      0.476      9.191      0.000       3.439       5.311
AGE           -0.0142      0.015     -0.969      0.333      -0.043       0.015
DIS           -1.4505      0.214     -6.786      0.000      -1.871      -1.030
RAD            0.1075      0.044      2.420      0.016       0.020       0.195
PTRATIO       -0.9467      0.142     -6.663      0.000      -1.226      -0.667
B              0.0098      0.003      3.257      0.001       0.004       0.016
LSTAT         -0.4294      0.056     -7.707      0.000      -0.539      -0.320
==============================================================================
Omnibus:                      148.371   Durbin-Watson:                   1.262
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              762.502
Skew:                           1.534   Prob(JB):                    2.66e-166
Kurtosis:                       9.085   Cond. No.                     1.05e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
# cols = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
#        'PTRATIO', 'B', 'LSTAT']
# for i in range(len(cols)):
#     arr = cols[:i] + cols[i + 1:]
#     model = ols(f'{cols[i]} ~ {'+'.join(arr)}', data=df).fit()
#     print("***********************************")
#     print(cols[i])
#     print(model.summary())


***********************************
CRIM
                            OLS Regression Results                            
Dep. Variable:                   CRIM   R-squared:                       0.426
Model:                            OLS   Adj. R-squared:                  0.408
Method:                 Least Squares   F-statistic:                     23.54
Date:                Sun, 02 Mar 2025   Prob (F-statistic):           4.21e-39
Time:                        15:24:56   Log-Likelihood:                -1323.8
No. Observations:                 394   AIC:                             2674.
Df Residuals:                     381   BIC:                             2725.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  

# Kiểm tra đa cộng tuyến

In [42]:
model = ols('MEDV ~ CRIM + ZN + INDUS + CHAS + RM + AGE + DIS + RAD + PTRATIO + B + LSTAT', data=df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.749
Model:                            OLS   Adj. R-squared:                  0.742
Method:                 Least Squares   F-statistic:                     103.5
Date:                Sun, 02 Mar 2025   Prob (F-statistic):          2.51e-107
Time:                        14:39:41   Log-Likelihood:                -1158.3
No. Observations:                 394   AIC:                             2341.
Df Residuals:                     382   BIC:                             2388.
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     16.9254      4.852      3.488      0.001       7.384      26.466
CRIM          -0.0849      0.034     -2.533      0.012      -0.151      -0.019
ZN             0.0403      0.014      2.788      0.006       0.012       0.069
INDUS         -0.1577      0.057     -2.786      0.006      -0.269      -0.046
CHAS           3.1254      0.950      3.289      0.001       1.257       4.994
RM             4.5934      0.484      9.493      0.000       3.642       5.545
AGE           -0.0312      0.014     -2.168      0.031      -0.060      -0.003
DIS           -1.1953      0.210     -5.696      0.000      -1.608      -0.783
RAD            0.0381      0.042      0.902      0.368      -0.045       0.121
PTRATIO       -0.7559      0.138     -5.481      0.000      -1.027      -0.485
B              0.0109      0.003      3.564      0.000       0.005       0.017
LSTAT         -0.4385      0.057     -7.705      0.000      -0.550      -0.327
==============================================================================
Omnibus:                      155.298   Durbin-Watson:                   1.211
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              871.384
Skew:                           1.585   Prob(JB):                    6.04e-190
Kurtosis:                       9.560   Cond. No.                     7.82e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.82e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [70]:
#  
from statsmodels.stats.outliers_influence import variance_inflation_factor

[(df.columns[i - 1], variance_inflation_factor(df, i)) for i in range(1, df.shape[1])]

[('CRIM', np.float64(2.7381463157233488)),
 ('ZN', np.float64(11.134973844694123)),
 ('INDUS', np.float64(1.1605434479325316)),
 ('CHAS', np.float64(77.73445556689477)),
 ('NOX', np.float64(154.86113098198456)),
 ('RM', np.float64(22.520216508270067)),
 ('AGE', np.float64(15.3106287263061)),
 ('DIS', np.float64(5.475842852148433)),
 ('RAD', np.float64(89.95192891642208)),
 ('PTRATIO', np.float64(22.474682971584468)),
 ('B', np.float64(12.353027733787707)),
 ('LSTAT', np.float64(27.15578043117442))]

# loại bỏ biến Tax vì có vif > 10

In [69]:
df.drop(columns=['TAX'], inplace=True)

In [67]:
X.shape

(394, 13)

In [33]:
[(df.columns[i - 1], float(variance_inflation_factor(X, i))) for i in range(1, X.shape[1])]

[('CRIM', 2.852309927713017),
 ('ZN', 14.263621604094793),
 ('INDUS', 1.147676919923875),
 ('CHAS', 78.19587146837218),
 ('NOX', 83.38739667510177),
 ('RM', 22.40573051836839),
 ('AGE', 14.367438543452744),
 ('DIS', 13.986225022429808),
 ('RAD', 58.485821213801586),
 ('TAX', 88.48314836650732),
 ('PTRATIO', 21.04718393865385),
 ('B', 11.340925461230494)]

In [36]:
model = ols('TAX ~ CRIM + ZN + INDUS + CHAS + NOX + RM + AGE + DIS + RAD + PTRATIO + B + LSTAT', data=df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    TAX   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.881
Method:                 Least Squares   F-statistic:                     242.9
Date:                Sun, 02 Mar 2025   Prob (F-statistic):          3.75e-170
Time:                        14:34:17   Log-Likelihood:                -2153.1
No. Observations:                 394   AIC:                             4332.
Df Residuals:                     381   BIC:                             4384.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    160.5566     73.124      2.196      0.029      16.779     304.334
CRIM          -0.2119      0.420     -0.504      0.614      -1.038       0.614
ZN             0.8745      0.181      4.831      0.000       0.519       1.230
INDUS          7.9408      0.751     10.576      0.000       6.465       9.417
CHAS         -30.0953     11.883     -2.533      0.012     -53.461      -6.730
NOX           30.3475     54.932      0.552      0.581     -77.661     138.356
RM            -6.9978      6.086     -1.150      0.251     -18.965       4.969
AGE            0.0914      0.187      0.488      0.626      -0.277       0.460
DIS           -0.6120      2.733     -0.224      0.823      -5.985       4.761
RAD           13.5642      0.568     23.878      0.000      12.447      14.681
PTRATIO        2.4433      1.817      1.345      0.179      -1.128       6.015
B             -0.0109      0.038     -0.283      0.778      -0.086       0.065
LSTAT          0.4370      0.712      0.614      0.540      -0.963       1.838
==============================================================================
Omnibus:                       70.891   Durbin-Watson:                   0.708
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              676.062
Skew:                           0.394   Prob(JB):                    1.57e-147
Kurtosis:                       9.369   Cond. No.                     1.05e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [37]:
1 / (1 - 0.884)

8.620689655172415