In [1]:
from pandas import read_csv
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from  sklearn.decomposition import PCA

In [2]:
df = read_csv('data\\housing_data_na.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [3]:
df.dropna(inplace=True)
df_X = df.drop(columns=['MEDV'])

## Gia tri rieng cua ma tran,  Vector rieng

In [29]:
pca = PCA(n_components=13)
pca.fit(df_X)

PCA(n_components=13)

In [30]:
# gia tri ring
pca.explained_variance_

array([3.06497684e+04, 6.05090729e+03, 8.31363708e+02, 2.72547791e+02,
       5.83795795e+01, 2.75936759e+01, 1.69381796e+01, 9.91964252e+00,
       3.25445638e+00, 1.20849908e+00, 2.32388154e-01, 5.97775027e-02,
       2.84451275e-03])

In [31]:
pca.explained_variance_ratio_

array([8.08228099e-01, 1.59561183e-01, 2.19228903e-02, 7.18702927e-03,
       1.53945752e-03, 7.27639565e-04, 4.46656318e-04, 2.61578936e-04,
       8.58193463e-05, 3.18678726e-05, 6.12802789e-06, 1.57632047e-06,
       7.50092170e-08])

In [32]:
pca.explained_variance_ / sum (pca.explained_variance_)

array([8.08228099e-01, 1.59561183e-01, 2.19228903e-02, 7.18702927e-03,
       1.53945752e-03, 7.27639565e-04, 4.46656318e-04, 2.61578936e-04,
       8.58193463e-05, 3.18678726e-05, 6.12802789e-06, 1.57632047e-06,
       7.50092170e-08])

In [33]:
# vector rieng (5 vetor)
pca.components_

array([[ 3.04131711e-02, -4.37853121e-02,  2.90970651e-02,
        -4.76893283e-05,  4.48504548e-04, -1.27074534e-03,
         8.31718185e-02, -6.50746554e-03,  4.43912657e-02,
         9.53079807e-01,  5.48944711e-03, -2.79954366e-01,
         2.47637982e-02],
       [-9.95894976e-03,  2.64062522e-04,  6.04030523e-03,
         1.94444999e-04, -1.27830997e-05, -5.32442228e-04,
        -1.21063793e-03, -2.33102902e-04,  6.63023413e-03,
         2.81897551e-01,  2.07515245e-03,  9.59322242e-01,
        -6.98303758e-03],
       [ 1.10252384e-02, -6.61974984e-01,  8.54219547e-02,
         7.90292188e-04,  1.71794828e-03, -5.01613850e-03,
         7.31446553e-01, -4.44227328e-02, -4.31710647e-03,
        -9.14345566e-02,  1.38713998e-02,  2.81867142e-02,
         8.93792777e-02],
       [ 2.96294898e-02,  7.43399003e-01, -6.16457859e-03,
         8.17002551e-04,  7.16588517e-04,  6.69650325e-03,
         6.64983328e-01, -3.30283512e-03, -2.19278466e-02,
        -2.22034156e-02, -3.48188234e

In [34]:
# giam chiec vector df_X
X_T = pca.transform(df_X)
X_T.shape

(394, 13)

In [35]:
np.corrcoef(X_T.T)

array([[ 1.00000000e+00,  6.02590813e-16, -2.86077092e-16,
        -1.93489179e-15,  2.91949223e-16,  9.84563192e-17,
        -1.44374454e-15,  1.08599136e-16,  1.22405597e-14,
        -7.59654496e-15, -1.10134289e-14,  2.05451226e-15,
        -3.98884658e-16],
       [ 6.02590813e-16,  1.00000000e+00,  3.58426740e-15,
         7.36153025e-15,  3.75624182e-15,  3.44488487e-15,
        -4.32957744e-15, -9.35511287e-15,  2.44727572e-14,
        -7.96833039e-15,  1.45656925e-15, -1.17844372e-15,
        -1.87501325e-15],
       [-2.86077092e-16,  3.58426740e-15,  1.00000000e+00,
        -9.23728535e-17, -1.34853452e-15, -8.58513289e-16,
        -6.88663698e-16,  4.80210238e-16, -8.72025000e-15,
         5.69030311e-15,  1.52464614e-14, -1.88613002e-14,
         1.62611689e-13],
       [-1.93489179e-15,  7.36153025e-15, -9.23728535e-17,
         1.00000000e+00,  5.90402482e-15, -8.97312678e-16,
         4.11920978e-16, -5.53846680e-15, -3.30609044e-15,
        -1.92867260e-15,  5.36143852e

In [36]:
y = df['MEDV'].values

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X_T,y)

In [41]:
lg = LinearRegression()
lg.fit(X_train, y_train)

LinearRegression()

In [42]:
lg.coef_, lg.intercept_

(array([-2.87992212e-02,  9.70225213e-03, -7.95230540e-02,  4.69186848e-02,
        -1.57946222e-01, -8.28756468e-01,  9.91064449e-02,  2.67330294e-01,
        -1.28908255e+00, -1.12066810e+00,  5.76544706e+00,  7.21231936e-01,
        -1.16039447e+01]),
 np.float64(22.309926193206444))

In [43]:
lg.score(X_train, y_train), lg.score(X_test, y_test)

(0.8261230479900815, 0.5173214967842976)